version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: build app
          command: ./gradlew ':app:assembleDebug'
      - store_artifacts:
          path: /app/build/outputs/apk/debug/app-debug.apk
          destination: /debug/app-debug.apk

  test:
    executor: android/android

    steps:
      - checkout
      - run:
          name: testing mvvm
          command: ./gradlew ':mvvm:testDebugUnitTest'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test



